spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/supplydb"
    username: "supplyuser"
    password: "supplypg"
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: DEBUG