spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/supplydb"
    username: "supplyuser"
    password: "supplypg"
    driver-class-name: org.postgresql.Driver

jwt:
  secret: jwtSupplier

#logging:
#  level:
#    root: DEBUG