CREATE TABLE IF NOT EXISTS "ADDRESS" (
   "ADDRESS_ID" BIGINT NOT NULL AUTO_INCREMENT,
   "COUNTRY" VARCHAR(50) NOT NULL,
   "CITY" VARCHAR(50) NOT NULL,
   "STREET" VARCHAR(50) NOT NULL,
   "BUILDING" INT NOT NULL,
   "TENANT_ID" BIGINT,
   PRIMARY KEY("ADDRESS_ID")
);

CREATE TABLE IF NOT EXISTS "SUPPLIER" (
    "ID" BIGINT NOT NULL AUTO_INCREMENT,
    "NAME" VARCHAR(50) NOT NULL,
    "ADDRESS_ID" BIGINT,
    PRIMARY KEY("ID")
);

CREATE TABLE IF NOT EXISTS "ORDER" (
    "ID" BIGINT NOT NULL AUTO_INCREMENT,
    "NAME" VARCHAR(50) NOT NULL,
    "PRICE" DECIMAL NOT NULL,
    "SUPPLIER_ID" BIGINT,
    PRIMARY KEY("ID")
);

CREATE TABLE IF NOT EXISTS "PRODUCT" (
    "ID" BIGINT NOT NULL AUTO_INCREMENT,
    "NAME" VARCHAR(50) NOT NULL,
    "PRICE" DECIMAL NOT NULL,
    "ORDER_ID" BIGINT,
    PRIMARY KEY("ID")
);

CREATE TABLE IF NOT EXISTS "RECIPIENT" (
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "ADDRESS_ID" BIGINT,
    UNIQUE ("ADDRESS_ID"),
    PRIMARY KEY("ID")
);

CREATE TABLE IF NOT EXISTS "SUPPLIER_RECIPIENT" (
    "SUPPLIER_ID" BIGINT,
    "RECIPIENT_ID" BIGINT
);